#!/bin/bash
# ============================================================
# tmux send-keys Helper Script (Generated by tmux-notify-wrapper)
# ============================================================
# tmux send-keys を安全に実行するヘルパースクリプト
#
# 機能:
#   - 2回分割送信の自動化（メッセージ送信 + Enter送信）
#   - 対象ペインの存在確認
#   - エラーハンドリング
#   - ログ出力
#
# 使用例:
#   ./scripts/notify.sh panzer-1:0.0 "新しい指示があります"
#   ./scripts/notify.sh panzer-hq:0.1 "報告書を確認されよ"
#
# 引数:
#   $1: 対象ペイン（session:window.pane 形式）
#   $2: 送信するメッセージ
#
# Generated by: tmux-notify-wrapper v1.0
# Generated at: 2026-01-29T15:47:00
# ============================================================

# ============================================================
# 設定
# ============================================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "${SCRIPT_DIR}")"
LOG_DIR="${PROJECT_DIR}/logs"
LOG_FILE="${LOG_DIR}/notify.log"

# 送信設定
WAIT_AFTER_MESSAGE=0.1
RETRY_COUNT=3
RETRY_DELAY=0.5

# 色設定（ターミナル出力用）
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ============================================================
# ログ関数
# ============================================================
log_to_file() {
    local level=$1
    local message=$2
    local timestamp
    timestamp=$(date "+%Y-%m-%dT%H:%M:%S")

    # ログディレクトリがなければ作成
    if [ ! -d "${LOG_DIR}" ]; then
        mkdir -p "${LOG_DIR}"
    fi

    echo "[${timestamp}] [${level}] ${message}" >> "${LOG_FILE}"
}

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
    log_to_file "INFO" "$1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
    log_to_file "SUCCESS" "$1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1" >&2
    log_to_file "WARN" "$1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
    log_to_file "ERROR" "$1"
}

log_debug() {
    # DEBUG レベルが有効な場合のみ出力
    if [ "${LOG_LEVEL}" = "DEBUG" ]; then
        echo -e "[DEBUG] $1"
        log_to_file "DEBUG" "$1"
    fi
}

# ============================================================
# 使用方法を表示
# ============================================================
usage() {
    echo "Usage: $0 <target_pane> <message>"
    echo ""
    echo "Arguments:"
    echo "  target_pane  Target pane in format: session:window.pane"
    echo "               Examples: panzer-1:0.0, panzer-hq:0.1"
    echo "  message      Message to send to the pane"
    echo ""
    echo "Examples:"
    echo "  $0 panzer-1:0.0 '新しい指示があります'"
    echo "  $0 panzer-hq:0.1 '報告書を確認されよ'"
    echo ""
    echo "Exit codes:"
    echo "  0  Success"
    echo "  1  Missing or invalid arguments"
    echo "  2  Session does not exist"
    echo "  3  Pane does not exist"
    echo "  4  Failed to send message"
    echo "  5  Failed to send Enter"
    exit 1
}

# ============================================================
# セッション存在確認
# ============================================================
check_session_exists() {
    local target=$1
    local session_name

    # session:window.pane からセッション名を抽出
    session_name=$(echo "${target}" | cut -d':' -f1)

    log_debug "Checking session: ${session_name}"

    if ! tmux has-session -t "${session_name}" 2>/dev/null; then
        log_error "Session '${session_name}' does not exist"
        return 2
    fi

    log_debug "Session '${session_name}' exists"
    return 0
}

# ============================================================
# ペイン存在確認
# ============================================================
check_pane_exists() {
    local target=$1

    log_debug "Checking pane: ${target}"

    # ペインが存在するか確認（list-panes でエラーが出なければ存在）
    if ! tmux list-panes -t "${target}" >/dev/null 2>&1; then
        log_error "Pane '${target}' does not exist"
        return 3
    fi

    log_debug "Pane '${target}' exists"
    return 0
}

# ============================================================
# send-keys を2回に分けて実行（リトライ機能付き）
# ============================================================
send_message() {
    local target=$1
    local message=$2
    local attempt=1
    local max_attempts=$((RETRY_COUNT + 1))

    while [ ${attempt} -le ${max_attempts} ]; do
        log_debug "Attempt ${attempt}/${max_attempts}"

        # 1回目: メッセージを送信
        if ! tmux send-keys -t "${target}" "${message}"; then
            log_error "Failed to send message to '${target}' (attempt ${attempt})"

            if [ ${attempt} -lt ${max_attempts} ]; then
                log_warn "Retrying in ${RETRY_DELAY} seconds..."
                sleep ${RETRY_DELAY}
                attempt=$((attempt + 1))
                continue
            else
                return 4
            fi
        fi

        # 少し待機（安定性向上のため）
        sleep ${WAIT_AFTER_MESSAGE}

        # 2回目: Enter を送信（C-m ではなく Enter を使用）
        if ! tmux send-keys -t "${target}" Enter; then
            log_error "Failed to send Enter to '${target}' (attempt ${attempt})"

            if [ ${attempt} -lt ${max_attempts} ]; then
                log_warn "Retrying in ${RETRY_DELAY} seconds..."
                sleep ${RETRY_DELAY}
                attempt=$((attempt + 1))
                continue
            else
                return 5
            fi
        fi

        # 成功
        return 0
    done

    return 4
}

# ============================================================
# メイン処理
# ============================================================
main() {
    local target_pane=$1
    local message=$2

    # 引数チェック
    if [ -z "${target_pane}" ] || [ -z "${message}" ]; then
        log_error "Missing required arguments"
        usage
    fi

    # セッション存在確認
    if ! check_session_exists "${target_pane}"; then
        exit 2
    fi

    # ペイン存在確認
    if ! check_pane_exists "${target_pane}"; then
        exit 3
    fi

    # メッセージ送信
    log_info "Sending message to '${target_pane}'"

    local result
    if send_message "${target_pane}" "${message}"; then
        log_success "Message sent successfully to '${target_pane}': ${message}"
        exit 0
    else
        result=$?
        log_error "Failed to send message to '${target_pane}'"
        exit ${result}
    fi
}

# スクリプト実行
main "$@"
